version: "3"
services:
  web:
    build: .
    ports:
      - 5000:5000
    # volumes:
    #   - .:/home/user
    # environment:
    #   FLASK_ENV: development
  redis:
    image: redis:6-alpine
